- hosts: ubantu
  become: true
  vars:
    - port: 60
  tasks:
    - name: install apache
      apt:
        name: 'apache2'
        state: 'latest'
    
#    - name: List Users and Groups
#      shell: |
#          echo "No of users in this system:" $(ls /home | wc -l)
#          echo "The Users are " $(ls /home)
#      register: result

    - name: copying the configuration file
      template:
        src: "ports.conf.j2"
        dest: "/etc/apache2/ports.conf"
      notify: restarts
     
#    - name: Adding index content to server
#      copy:
#        content: "{{ result.stdout }}"
#        dest: "/var/www/html/index.html"      

    - name:  start ubantu
      service:
        name: 'apache2'
        state: 'started'

  handlers:
    - name: restarts
      service: 
        name: 'apache2'
        state: 'restarted'
