---
# tasks file for ansible-java

- name: Load package variables
  include_vars: "{{ ansible_distribution}}.yml"
  when: ansible_distribution == 'CentOS'

# Setup/Install tasks

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Environment variable setup.
- name: Set JAVA_HOME if configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home


   
